import { Inter } from "next/font/google";
import { authOptions } from "./api/auth/[...nextauth]";
import "./globals.css";
import ClientProvider from "@/components/ClientProvider";
import Login from "@/components/Login";
import SessionProvider from "@/components/SessionProvider";
import SideBar from "@/components/SideBar";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);

  console.log(session);
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              {/* Sidebar*/}
              <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
                <SideBar />
              </div>
              {/* ClientProvider - Notifications*/}
              <ClientProvider />

              <div className="bg-[#343541] flex-1"> {children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
