//import "./globals.css";
import { Inter } from "next/font/google";
import ClientProvider from "@/components/ClientProvider";
import Login from "@/components/Login";
import SessionProvider from "@/components/SessionProvider";
import SideBar from "@/components/SideBar";
import "@rainbow-me/rainbowkit/styles.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Header } from "~~/components/Header";
import { MetaHeader } from "~~/components/MetaHeader";
import "~~/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Geppetto",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <MetaHeader />
      <body className={inter.className}>
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <div className="flex flex-col">
              <Header />
              {/* Sidebar*/}
              <ClientProvider />
              <div className="flex flex-row shrink">
                <div className=" md:min-w-[20rem]">
                  <SideBar />
                </div>
                {/* ClientProvider - Notifications*/}

                <div className="w-full bg-primary "> {children}</div>
              </div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
